#ifndef P
#define P(x)
#endif
#ifndef H
#define H(a,b)
#endif
H(termios,x)
P(ICANON) P(ECHO) P(ISIG) P(ICRNL) P(INPCK) P(ISTRIP) P(OPOST)
P(VINTR) P(VQUIT) P(VERASE) P(VKILL) P(VEOF) P(VTIME) P(VMIN)
P(TCSANOW) P(IEXTEN) P(BRKINT) P(IXON) P(CS8)

H(ioctl,x)
P(TCGETS) P(TCSETS) P(TIOCGWINSZ) P(TIOCSWINSZ)
P(TIOCNOTTY)

H(ioctl,x)
P(O_RDONLY) P(O_WRONLY) P(O_RDWR) P(O_NONBLOCK) P(O_APPEND) P(O_CREAT) P(O_EXCL) P(O_TRUNC)

H(syscall,d)
P(SYS_read) P(SYS_write) P(SYS_open) P(SYS_close) P(SYS_stat) P(SYS_fstat) P(SYS_lseek) P(SYS_mmap) P(SYS_munmap) P(SYS_brk) P(SYS_exit) P(SYS_fork)

H(syscall,d)
P(SIGINT) P(SIGTERM) P(SIGKILL) P(SIGQUIT) P(SIGCHLD) P(SIGPIPE)
P(SIGHUP) P(SIGALRM) P(SIGSEGV) P(SIGIO)

H(sa_flags,x)
P(SA_SIGINFO) P(SA_UNSUPPORTED) P(SA_EXPOSE_TAGBITS)

H(socket,x)
P(AF_INET) P(AF_INET6) P(AF_UNIX) P(SOCK_STREAM) P(SOCK_DGRAM) P(SOCK_RAW)
P(SOL_SOCKET) P(SO_REUSEADDR) P(SO_KEEPALIVE) P(SO_RCVBUF) P(SO_SNDBUF)
P(IPPROTO_TCP) P(IPPROTO_UDP) P(TCP_NODELAY)

H(stat,o)
P(S_IFREG) P(S_IFDIR) P(S_IRUSR) P(S_IWUSR) P(S_IXUSR) P(S_IRGRP) P(S_IWGRP) P(S_IXGRP) P(S_IROTH) P(S_IWOTH) P(S_IXOTH)

H(poll,x)
P(POLLIN) P(POLLOUT) P(POLLERR) P(POLLHUP) P(EPOLLIN) P(EPOLLOUT) P(EPOLLERR) P(EPOLLHUP) P(EPOLLET)

H(net/if,x)
P(IFF_UP) P(IFF_BROADCAST) P(IFF_RUNNING) P(IFF_MULTICAST)

H(linux tun,x)
P(IFF_TUN) P(IFF_TAP) P(IFF_NO_PI)

#undef P
