dir/src:=bin lib tst
src/c++:=$(foreach d,$(dir/src),$(wildcard $d/*.cc))
raw/asm:=$(foreach d,$(dir/src),$(wildcard $d/*.SS))
src/asm:=$(filter-out $(src/c++:.cc=.SS),$(raw/asm))
src/mod:=$(src/c++:.cc=) $(src/asm:.SS=)
src/exe:=$(filter bin/%,$(src/mod)) $(filter tst/%,$(src/mod))
all/c++:=$(src/c++)
all/dep:=$(src/c++:.cc=.dd)
all/cpp:=$(all/c++:.cc=.ii)
gen/asm:=$(src/c++:.cc=.SS)
all/asm:=$(src/asm) $(gen/asm)
all/obj:=$(all/asm:.SS=.oo)
lib/obj:=$(filter lib/%,$(all/obj))
all/exe:=$(src/exe)

all: $(all/exe)
