#include "syscall.hh"
#include "errno.hh"
#include "fmt.hh"
#include "itr-ops.hh"
struct set_bool {
  bool &val;
  set_bool(bool &val)
    : val(val)
  {
    val=true;
  }
  ~set_bool()
  {
    val=false;
  };
};
namespace itr {
void fuck_off(int res, char const *msg) {
  sys::die(res,msg);
};
};
void sys::err_ignore(sys::errno_t err)
{
};
void sys::err_log(sys::errno_t err)
{
  static bool recurse=false;
  if(recurse)
    return;
  set_bool setter(recurse);
  sys::write(2,"setting error to: ");
  sys::write(2,fmt::fmt_t((long)err));
  sys::write(2,"\n\n");
};
void sys::err_fatal(errno_t err) {
  sys::write(2,"FROM: ");
  sys::write(2,fmt::fmt_t(getpid()));
  sys::write(2,"  FATAL ERROR: ");
  sys::write(2,fmt::fmt_t(err));
  sys::write(2,"\n");
  sys::write(2,strerror(err));
  sys::write(2,"\n");
  pexit(5,"err_fatal");
  std::abort();
  kill(getpid(),9);
};
void sys::set_errno(errno_t err, errhand_t hand)
{
  if(err<0 && err>-4096) {
    err=(errno_t)-err;
  } else if (err>uint64_t(-4096)) {
    err=(errno_t)-err;
  };
  errno=err;
  hand(err);
}
namespace sys {
  void throw_errno(errno_t err);
};
void sys::throw_errno(errno_t err){
  sys::set_errno(err);
  char buf[1023]="setting error to: ";
  char *pos=buf+itr::len(buf);
  char *end=buf+sizeof(buf)-1;
  *--end=0;
  pos=itr::copy(pos,end,fmt::fmt_t(err));
  pos=itr::copy(pos,end," ( ");
  pos=itr::copy(pos,end,sys::strerror(sys::errno));
  pos=itr::copy(pos,end," )\n");
  exit(-1);
};
namespace sys {
  inline bool err_retry_on_transient(errno_t err) {
    static collect::bitset_t<128> transient = {
      EINTR,
      EAGAIN,
      EWOULDBLOCK,
    };
    return transient.is_set(err);
  }
  void err_die_if_stdin_tty(sys::errno_t err) {
    if(isatty(0))
      pexit(3,"stdin is a tty, but can't open /dev/tty");
  }
  errno_t errno;
  void perror(const char *msg)
  {
    static const char *null="";
    perror(null,msg);
  };
  void die(int err, const char *msg1, const char *msg2)
  {
    perror(msg1,msg2);
    exit(err);
  };
  void die(int err, const char *msg)
  {
    write(2,msg);
    exit(err);
  };
  void die(const char *msg){
    die(1,msg);
  };
  void pexit(int err, const char *msg1, const char *msg2)
  {
    write(2,msg1);
    write(2,msg2);
    exit(err);
  };
  void pexit(int err, const char *msg)
  {
    perror(msg);
    exit(err);
  };
  void perror(const char *msg1, const char *msg2)
  {
    if(msg1) {
      write(2,msg1);
      write(2,":");
    };
    if(msg2) {
      write(2,msg2);
      write(2,":");
    };
    write(2,fmt::fmt_t(errno));
    write(2,"  --  ",6);
    write(2,strerror(errno));
  };
  void pexit(const char *msg1, const char *msg2)
  {
    perror(msg1,msg2);
    exit(1);
  };
  void assert_fail(const char *cond, const char *file, unsigned line){
    write(2,file);
    write(2,":");
    write(2,fmt::fmt_t(line));
    write(2,": assertion (");
    write(2,cond);
    write(2,") failed");
    exit(1);
  };
};
// do not edit this file.  It will be regenerated.

typedef char const *msg_t;

static msg_t strerror_v[]={
 "Unknown Error(###)",
 "Operation not permitted",
 "No such file or directory",
 "No such process",
 "Interrupted system call",
 "Input/output error",
 "No such device or address",
 "Argument list too long",
 "Exec format error",
 "Bad file descriptor",
 "No child processes",
 "Resource temporarily unavailable",
 "Cannot allocate memory",
 "Permission denied",
 "Bad address",
 "Block device required",
 "Device or resource busy",
 "File exists",
 "Invalid cross-device link",
 "No such device",
 "Not a directory",
 "Is a directory",
 "Invalid argument",
 "Too many open files in system",
 "Too many open files",
 "Inappropriate ioctl for device",
 "Text file busy",
 "File too large",
 "No space left on device",
 "Illegal seek",
 "Read-only file system",
 "Too many links",
 "Broken pipe",
 "Numerical argument out of domain",
 "Numerical result out of range",
 "Resource deadlock avoided",
 "File name too long",
 "No locks available",
 "Function not implemented",
 "Directory not empty",
 "Too many levels of symbolic links",
 "Unknown error 41",
 "No message of desired type",
 "Identifier removed",
 "Channel number out of range",
 "Level 2 not synchronized",
 "Level 3 halted",
 "Level 3 reset",
 "Link number out of range",
 "Protocol driver not attached",
 "No CSI structure available",
 "Level 2 halted",
 "Invalid exchange",
 "Invalid request descriptor",
 "Exchange full",
 "No anode",
 "Invalid request code",
 "Invalid slot",
 "Unknown error 58",
 "Bad font file format",
 "Device not a stream",
 "No data available",
 "Timer expired",
 "Out of streams resources",
 "Machine is not on the network",
 "Package not installed",
 "Object is remote",
 "Link has been severed",
 "Advertise error",
 "Srmount error",
 "Communication error on send",
 "Protocol error",
 "Multihop attempted",
 "RFS specific error",
 "Bad message",
 "Value too large for defined data type",
 "Name not unique on network",
 "File descriptor in bad state",
 "Remote address changed",
 "Can not access a needed shared library",
 "Accessing a corrupted shared library",
 ".lib section in a.out corrupted",
 "Attempting to link in too many shared libraries",
 "Cannot exec a shared library directly",
 "Invalid or incomplete multibyte or wide character",
 "Interrupted system call should be restarted",
 "Streams pipe error",
 "Too many users",
 "Socket operation on non-socket",
 "Destination address required",
 "Message too long",
 "Protocol wrong type for socket",
 "Protocol not available",
 "Protocol not supported",
 "Socket type not supported",
 "Operation not supported",
 "Protocol family not supported",
 "Address family not supported by protocol",
 "Address already in use",
 "Cannot assign requested address",
 "Network is down",
 "Network is unreachable",
 "Network dropped connection on reset",
 "Software caused connection abort",
 "Connection reset by peer",
 "No buffer space available",
 "Transport endpoint is already connected",
 "Transport endpoint is not connected",
 "Cannot send after transport endpoint shutdown",
 "Too many references: cannot splice",
 "Connection timed out",
 "Connection refused",
 "Host is down",
 "No route to host",
 "Operation already in progress",
 "Operation now in progress",
 "Stale file handle",
 "Structure needs cleaning",
 "Not a XENIX named type file",
 "No XENIX semaphores available",
 "Is a named type file",
 "Remote I/O error",
 "Disk quota exceeded",
 "No medium found",
 "Wrong medium type",
 "Operation canceled",
 "Required key not available",
 "Key has expired",
 "Key has been revoked",
 "Key was rejected by service",
 "Owner died",
 "State not recoverable",
 "Operation not possible due to RF-kill",
 "Memory page has hardware error",
 "Unknown error 134",
};


static size_t strerror_c = sizeof(strerror_v)/sizeof(strerror_v[0]);
namespace sys {
  using str::c_str;
  c_str no_err("No Error");
  c_str last_err;
  const c_str strerror(errno_t err) {
    if(!err)
      last_err=no_err;
    else if(err<strerror_c)
      last_err=strerror_v[err];
    else
      last_err=strerror_v[0];
    return last_err;
  };  
}

