#!/bin/bash

die(){
  echo $(printf "$@") >&2;
  exit 1;
}
n=$(($#))
for i; do
  set -- "$@" ${i#lib/}  
done
shift ${n}

cd lib
case "$1" in
  (*.a|*.aa)
    lib="$1"
    
    shift
    ;;
  (*)
    die "bad lib name %q" "$l"
    ;;
esac
for s; do
  case "$s" in
    (*.oo)
      test -f "$s" || die "missing file %s" $s
      ;;
    (*)
      die "bad archive member name: %q" "$s"
      ;;
  esac
done

ar r $lib "$@"
ranlib "$lib"
ar t "$lib" | sed "s,^,$lib: $(dirname $lib)/," > /dev/null
