#!/bin/bash

die(){ echo $(printf "$@") >&2; exit 1; }
for o; do
  case "$o" in
    (*.oo)
      r=${o%.oo}
      s=$r.ii
      d=$o.d
      ;;
    (*)
      die "no support for file %q\n" "$o"
      ;;
  esac
  set -- -o $o $s 
  set -- "$@" @etc/cxxflags
  set -- "$@" -MD -MF $d -MP -MT $o
  set -- "g++" "$@" -c
  #printf ' (%s)\n' "$@"
  if ! "$@"; then
    die "$* returned %d" $?
  fi
done
