#!/usr/bin/perl
use warnings;
use strict;
use autodie(qw(:all));
$|++;
$\="\n";

die "$@" if "$@";

my $fn = "lib/strerror_list.cc";
open(STDOUT,">$fn.new");
print "// do not edit this file.  It will be regenerated.\n";
print "#include <c_str.hh>\n";
print "\n";
print "static c_str strerror_v[]={\n";
print "  \"Unknown Error(###)\",\n";
my $i=1;
while($i) {
  $!=$i;
  for("$!") {
    if( $i>134 && /Unknown Error/i ) {
      $i=0;
    } else {
      print " \"$_\",";
      $i++;
    };
  };
};
print "};\n";
print <DATA>;
rename("$fn.new",$fn);
__DATA__

static size_t strerror_c = sizeof(strerror_v)/sizeof(strerror_v[0]);
namespace sys {
  c_str no_err(L("No Error"));
  const c_str &strerror(errno_t err) {
    if(!err)
      return no_err;
    else if(err<strerror_c)
      return strerror_v[err];
    else
      return strerror_v[0];
  };  
}
