#!/usr/bin/sudo /bin/bash 

rm -fr nodes
mkdir nodes
cd nodes
mknod fifo      p
mknod nvme0n1p1 b 259 1
mknod tty1      c  4   1
perl -e 'use IO::Socket::UNIX; IO::Socket::UNIX->new( Listen=>1, Local=>"sock" );';

exit 0
s sock

prw-r--r-- 1 nn   nn        0 Sep  7 15:13 fifo
brw------- 1 root root 259, 1 Sep  7 03:32 nvme0n1p1
srwxr-xr-x 1 nn   nn        0 Sep  7 15:13 sock
crw------- 1 root tty    4, 1 Sep  7 03:32 tty1
