#!/usr/bin/perl
use warnings;
use strict;
use autodie(qw(:all));
$|++;
$\="\n";

our(@msg);
eval {
for my $i (1..255)
{ 
  local $!=$i;
  $msg[$i]="$i:$!" unless "$!" =~ /unknown error/i;
}
};
die "$@" if "$@";

my $fn = "lib/strerror_list.cc";
open(STDOUT,">$fn.new");
print STDERR "$fn:1:generated file!";
print qq(// do not edit this file.  It will be regenerated.
#  @{[__LINE__]} "@{[__FILE__]}"
#include <c_str.hh>

static c_str strerror_v[]={);
print qq(  "Unknown Error(###)");
for(@msg) {
  print qq(  "$_",) if defined;
};
print q(
};

static size_t strerror_c = sizeof(strerror_v)/sizeof(strerror_v[0]);
namespace sys {
  c_str no_err(L("No Error"));
  const c_str &strerror(errno_t err) {
    if(!err)
      return no_err;
    else if(err<strerror_c)
      return strerror_v[err];
    else
      return strerror_v[0];
  };  
}
);
rename("$fn.new",$fn);
use Data::Dumper;
